# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatsql.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatsql.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rchatsql.proto\"\x1c\n\nSqlRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"H\n\x0bSqlResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\trawResult\x18\x02 \x01(\t\x12\x17\n\x0fprocessedResult\x18\x03 \x01(\t28\n\x0b\x43hatSqlGrpc\x12)\n\x0cSqlPredictor\x12\x0b.SqlRequest\x1a\x0c.SqlResponseb\x06proto3'
)




_SQLREQUEST = _descriptor.Descriptor(
  name='SqlRequest',
  full_name='SqlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prompt', full_name='SqlRequest.prompt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=45,
)


_SQLRESPONSE = _descriptor.Descriptor(
  name='SqlResponse',
  full_name='SqlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='SqlResponse.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rawResult', full_name='SqlResponse.rawResult', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedResult', full_name='SqlResponse.processedResult', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['SqlRequest'] = _SQLREQUEST
DESCRIPTOR.message_types_by_name['SqlResponse'] = _SQLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SqlRequest = _reflection.GeneratedProtocolMessageType('SqlRequest', (_message.Message,), {
  'DESCRIPTOR' : _SQLREQUEST,
  '__module__' : 'chatsql_pb2'
  # @@protoc_insertion_point(class_scope:SqlRequest)
  })
_sym_db.RegisterMessage(SqlRequest)

SqlResponse = _reflection.GeneratedProtocolMessageType('SqlResponse', (_message.Message,), {
  'DESCRIPTOR' : _SQLRESPONSE,
  '__module__' : 'chatsql_pb2'
  # @@protoc_insertion_point(class_scope:SqlResponse)
  })
_sym_db.RegisterMessage(SqlResponse)



_CHATSQLGRPC = _descriptor.ServiceDescriptor(
  name='ChatSqlGrpc',
  full_name='ChatSqlGrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='SqlPredictor',
    full_name='ChatSqlGrpc.SqlPredictor',
    index=0,
    containing_service=None,
    input_type=_SQLREQUEST,
    output_type=_SQLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSQLGRPC)

DESCRIPTOR.services_by_name['ChatSqlGrpc'] = _CHATSQLGRPC

# @@protoc_insertion_point(module_scope)
