# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb import chatsql_pb2 as chatsql__pb2


class ChatSqlGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SqlPredictor = channel.unary_unary(
                '/ChatSqlGrpc/SqlPredictor',
                request_serializer=chatsql__pb2.SqlRequest.SerializeToString,
                response_deserializer=chatsql__pb2.SqlResponse.FromString,
                )


class ChatSqlGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SqlPredictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatSqlGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SqlPredictor': grpc.unary_unary_rpc_method_handler(
                    servicer.SqlPredictor,
                    request_deserializer=chatsql__pb2.SqlRequest.FromString,
                    response_serializer=chatsql__pb2.SqlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatSqlGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatSqlGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SqlPredictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatSqlGrpc/SqlPredictor',
            chatsql__pb2.SqlRequest.SerializeToString,
            chatsql__pb2.SqlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
